# Generated by Django 6.0.3 on 2026-05-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_expensesdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydata',
            name='income',
            field=models.FloatField(),
        ),
    ]
